package com.dinukaly.velo.entity;

public enum AgentStepType {
    VALIDATING_CONTEXT,
    CHECKING_INDEX,
    PLANNING,
    LEXICAL_SEARCH,
    SEMANTIC_SEARCH,
    FILESYSTEM_SEARCH,
    READING_FILE,
    ANALYZING_CODE,
    GENERATING_EDITS,
    BUILDING_DIFF,
    WAITING_FOR_APPROVAL,
    PREFLIGHTING,
    APPLYING_CHANGES,
    REINDEXING_FILES,
    RUNNING_VERIFICATION,
    COMPLETED,
    WARNING
}
