package com.dinukaly.velo.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * The top-level entity representing a structured set of code changes proposed by the AI agent.
 *
 * Each AgentRun may produce exactly one AgentProposal.
 * A proposal consists of one or more AgentProposalFiles, each containing one or more AgentProposalHunks.
 * The user reviews and accepts/rejects individual hunks before the Safe-Apply phase writes them to disk.
 */
@Entity
@Table(name = "agent_proposals", indexes = {
        @Index(name = "idx_agent_proposals_run", columnList = "run_id", unique = true),
        @Index(name = "idx_agent_proposals_status", columnList = "status")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AgentProposal {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** The AgentRun that produced this proposal. One-to-one (one run = one proposal). */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "run_id", nullable = false, unique = true)
    private AgentRun run;

    /** Current lifecycle status of the proposal. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private ProposalStatus status;

    /**
     * Short natural-language description of what this proposal does.
     * Generated by the AI and shown to the user in the review panel header.
     */
    @Column(columnDefinition = "TEXT")
    private String description;

    /**
     * Total number of hunks across all files in this proposal.
     * Denormalised for quick badge display in the UI.
     */
    @Column(name = "total_hunk_count", nullable = false)
    private int totalHunkCount;

    /**
     * Number of hunks the user has ACCEPTED.
     * Incremented by ProposalService.decideHunk().
     */
    @Column(name = "accepted_hunk_count", nullable = false)
    private int acceptedHunkCount;

    /**
     * Number of hunks the user has REJECTED.
     * Incremented by ProposalService.decideHunk().
     */
    @Column(name = "rejected_hunk_count", nullable = false)
    private int rejectedHunkCount;

    /**
     * Schema version of the proposal payload — allows safe migrations if the hunk
     * format changes between releases.
     */
    @Column(name = "proposal_schema_version", nullable = false)
    private int proposalSchemaVersion;

    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    @Column(nullable = false)
    private Instant updatedAt;

    /** All files changed by this proposal. */
    @OneToMany(mappedBy = "proposal", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("filePath ASC")
    @Builder.Default
    private List<AgentProposalFile> files = new ArrayList<>();

    @PrePersist
    public void prePersist() {
        createdAt = Instant.now();
        updatedAt = Instant.now();
        if (status == null) status = ProposalStatus.PENDING_REVIEW;
        if (proposalSchemaVersion == 0) proposalSchemaVersion = 1;
    }

    @PreUpdate
    public void preUpdate() {
        updatedAt = Instant.now();
    }
}
